import dotenv from "dotenv";

dotenv.config();

const PORT = process.env.PORT || 3000;
const MONGODB_URI = process.env.MONGODB_URI;
const WEBHOOK_SECRET = process.env.WEBHOOK_SECRET;
const CLERK_SECRET_KEY = process.env.CLERK_SECRET_KEY;
const CLERK_PUBLISHABLE_KEY = process.env.CLERK_PUBLISHABLE_KEY;
const NODE_ENV = process.env.NODE_ENV;
const DEV_FRONTEND_URL=process.env.DEV_FRONTEND_URL
const DEV_BACKEND_URL=process.env.DEV_BACKEND_URL
const PROD_BACKEND_URL=process.env.PROD_BACKEND_URL
const PROD_FRONTEND_URL=process.env.PROD_FRONTEND_URL

export { PORT, MONGODB_URI, WEBHOOK_SECRET, CLERK_SECRET_KEY, CLERK_PUBLISHABLE_KEY, NODE_ENV, DEV_FRONTEND_URL, DEV_BACKEND_URL, PROD_BACKEND_URL, PROD_FRONTEND_URL };
